# Site settings
url:                    http://tech.gohcl.com
domain:                 tech.gohcl.com
name:                   HCL Technology Services
title:                  HCL Technology Services
description:            Team blog for the Technology Services team at Health Care Logistics.

author:                 Kurt Wolf
email:                  kwolf@gohcl.com

twitter:                gohcltech
github:                 gohcltech

sitemap:
    include:            ["/index.html"]

# Where things are
source:                 ./
destination:            ./_site
layouts_dir:            ./_layouts
plugins_dir:            ./_plugins

# Handling Reading
safe:                   true
include:                [".htaccess"]
exclude:                [
                            "bin",
                            "bower_components",
                            "node_modules",
                            "gulp-tasks",
                            "bower.json",
                            "Gemfile",
                            "Gemfile.lock",
                            "gulpfile.js",
                            "package.json",
                            "README.md"
                        ]
keep_files:             [
                            "assets/css",
                            "assets/fonts",
                            "assets/img",
                            "assets/js"
                        ]
encoding:               "utf-8"
markdown_ext:           "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts:            null
limit_posts:            0
future:                 true
unpublished:            false

# Plugins
whitelist:              []
gems:                   []

# Build settings
markdown:               kramdown
# ighlighter:            rouge
permalink:              /:year/:month/:title/
#permalink:              pretty
#post_dirs:              false
paginate_path:          /page:num
paginate:               10
# timezone:               America/New_York
recent_post_limit:      5

# quiet:                  false
# defaults:               []
